ipfs/someguy

- Dockerfile
- main.go
Port 8080 no longer hard coded in the CLI, but it's currently left as the default and is made explicit in the Docker file.
Targeted after #6
> feat: custom port

- README.md
- go.mod
> refactor: ipfs-shipyard/ → ipfs/

- README.md
- docs/environment-variables.md
- main.go
> feat: configure server with env variables

- Dockerfile
- docs/environment-variables.md
- main.go
- server.go
Closes #47.
Changes default port to 8190, and changes from port to listen address config.
After this, we may need to update the infra.
> refactor!: use listen address instead of port, change default

- go.mod
- go.sum
Bubble up Boxo to include cache-related headers https://github.com/ipfs/boxo/pull/584
> chore: update boxo to include cache headers

- go.mod
- server.go
- server_routers.go
- server_routers_test.go
> feat: filter out private and loopback addresses

- .github/workflows/changelog.yml
- .github/workflows/docker.yml
- CHANGELOG.md
- README.md
Based on Rainbow PRs:
- https://github.com/ipfs/rainbow/pull/123
- https://github.com/ipfs/rainbow/pull/122
> Changelog & Docker on Release

- CHANGELOG.md
- go.mod
- go.sum
Includes fix: https://github.com/ipfs/boxo/pull/609
> chore: update boxo

- .github/workflows/docker.yml
- .github/workflows/releaser.yml
This is the same set of changes as introduced in https://github.com/ipfs/rainbow/pull/138
I have already set up the UCI_GITHUB_TOKEN secret. The token belongs to web3-bot and is limited to access to someguy only.
> refactor(ci): automate docker releases on tag pushes

- CHANGELOG.md
- go.mod
- server.go
This PR aims to fix interrupt handling when <kbd>^C</kbd> is hit in terminal (a regression detected in https://github.com/ipfs/someguy/pull/72, so PR against that). 
It was not possible to stop `./someguy start` via regular interrupt, so I've ported interrupt signal handling from rainbow. 
Graceful shutdown should help us avoid caching truncated streaming responses. 
Tested with `ab` tool, works as expected.
> fix: graceful shutdown and interrupt handling

- CHANGELOG.md
- version.json
> chore: release v0.3.0

- CHANGELOG.md
- docs/environment-variables.md
- main.go
- server.go
- version.json
This PR proposes a patch release v0.4.1 that enables UPnP/hole punching bringing someguy closer to what Kubo does.
iiuc this does not hurt, and should help if someone is running someguy locally  or behind some restrictive NAT without public addr + hole punching is necessary to reach other NATd peers
> fix: enable hole punching and libp2p listener config

- internal/fd/sys_unix.go
`go:build` means the same, and that notation seems to be preferable:
https://go.googlesource.com/proposal/+/master/design/draft-gobuild.md
> chore: remove redundant buildtag

- CHANGELOG.md
- go.mod
- go.sum
- version.json
- Add supports for [IPIP-484](https://github.com/ipfs/specs/pull/484)
- Upgrade to [Boxo v0.24.0](https://github.com/ipfs/boxo/releases/tag/v0.24.0)
https://github.com/ipfs/specs/pull/484
> feat: opt-in protocol and address filtering (IPIP-484)

- CHANGELOG.md
- server.go
- version.go
- version.json
Because we don't have HTTP retrieval client in golang (boxo) yet, the [`DefaultProtocolFilter`](https://github.com/ipfs/boxo/blob/29598b2babb86cf508adb35940436db6445ff032/routing/http/client/client.go#L37) in `boxo/routing/http/client` does not include `transport-ipfs-gateway-http` yet.
This had unintended consequence at delegated-ipfs.dev because  someguy as a proxy CLIENT to `https://cid.contact/routing/v1`, was running with default filters and as a client, was filtering `transport-ipfs-gateway-http` out.
Then, when acting as delegated routing SERVER, it no longer had them, which made these results unavailable to JS clients, even when they DO have HTTP support (e.g. SW gateway at https://inbrowser.link), even if they included it in explicit …
> fix: no implicit filtering of proxied IPNI results

- version.json
minor release with new features:
- tracing
- per route metrics
- upgrade go-libp2p-kad-dht  to 0.28.1
- upgrade boxo to latest main
- DHT request timeouts
> Release v0.6.0

- server_routers_test.go
This is one of the tests that frequently fails due to a race condition.
> fix: flaky test

- CHANGELOG.md
- server.go
- server_cached_router.go
This fixes a regression introduced with the cached router.
Because the `cachedRouter` was wrapping `sanitizeRouter`, any providers that has no addresses, were thus getting populated straight from cache without going through `sanitizeRouter`.
This resulted in us returning providers with private IPs.
This PR ensures that whatever the cached router spews out, gets properly sanitised.
- `sanitizeRouter` removes private IPs, but it doesn't remove records that have **no IPs**.  In theory, there's might be an edge case where we find records that only contain private IPs, that are then removed by `sanitizeRouter`, leading frontends/consumers of this to issue a subsequent calls. This seems pretty unlikely. 
- Is it even possible for would a peer show up in `dht.FindPeer` with only private IPs (if …
> fix: filter public ips

- CHANGELOG.md
- server.go
Someguy already supports delegated publishing of IPNS records. But currently, cross origin requests are blocked. By enabling, we can have tools make use of this from other origins.
> feat: enable cors for put requests

- CHANGELOG.md
- docs/environment-variables.md
- http_block_provider.go
- http_block_router.go
- http_block_router_test.go
- main.go
- server.go
- server_test.go
fixes #109
Start someguy as `/routing/v1` proxy for gateway at `dag.w3s.link`:
```console
$ SOMEGUY_HTTP_BLOCK_PROVIDER_ENDPOINTS="https://dag.w3s.link" SOMEGUY_HTTP_BLOCK_PROVIDER_PEERIDS="QmaSDHYKwuUKTvnsGwqutEZWg5jrpzLJhDHaYRQ9VvrDyZ" SOMEGUY_DHT=disabled ./someguy start
```
CID that is at `dag.w3s.link`:
```console
$ curl http://127.0.0.1:8190/routing/v1/providers/bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi -H "Accept: application/x-ndjson"
{"Addrs":["/dns/dag.w3s.link/tcp/443/tls/http"],"ID":"QmaSDHYKwuUKTvnsGwqutEZWg5jrpzLJhDHaYRQ9VvrDyZ","Protocols":["transport-ipfs-gateway-http"],"Schema":"peer"}
```
If CID is not at  gateway, there will be no providers returned.
> feat: enable using an HTTP block provider as a routing backend

- CHANGELOG.md
- version.json
> chore: release v0.9.1

- .github/workflows/docker.yml
- Dockerfile
Chore cleanup of warnings from https://github.com/ipfs/someguy/actions/runs/17711695295/job/50331211534 + applying modern approach that already works in Kubo
- update to go 1.25
- add buildkit syntax and cache mounts
- fix deprecated ENV syntax
- switch from local to gha cache in workflow
> chore: modernize docker build
